// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvfofBWsrzz8PSLMlFSx8jxhPdsnqR0M',
    appId: '1:1020829062919:web:41d1a5b51a8546c71317a2',
    messagingSenderId: '1020829062919',
    projectId: 'proje-database-android',
    authDomain: 'proje-database-android.firebaseapp.com',
    storageBucket: 'proje-database-android.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPcjFfpih6bOH9qWxj2PiUpxWulLhZZ8E',
    appId: '1:1020829062919:android:981caa6e8142bb4e1317a2',
    messagingSenderId: '1020829062919',
    projectId: 'proje-database-android',
    storageBucket: 'proje-database-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVzYYjQZd8i5l6vgj4nAi1Ndf-E19qYQ',
    appId: '1:1020829062919:ios:f34de136a948cc261317a2',
    messagingSenderId: '1020829062919',
    projectId: 'proje-database-android',
    storageBucket: 'proje-database-android.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVzYYjQZd8i5l6vgj4nAi1Ndf-E19qYQ',
    appId: '1:1020829062919:ios:04134632d658f8051317a2',
    messagingSenderId: '1020829062919',
    projectId: 'proje-database-android',
    storageBucket: 'proje-database-android.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
